permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: ":num"
baseurl: ""

title: "Cheenwe"
email: "cxhyun@126.com"
description: "A Ruby Coder"
github_username:  "cheenwe"
swiftype_searchId: "9TDAXeK2smEEtWndRZJB"
disqus_shortname: "cheenwecn"



# url: "http://cheenwe.github.io"
# imgrepo: "http://cheenwe.github.io/static/img"
url: "http://127.0.0.1:4000"
imgrepo: "http://127.0.0.1:4000/static/img"

